#ifndef __DEFAULTS_H__
#define __DEFAULTS_H__

/*
 * CharmBH: defaults.h
 * Default values for all the simulation parameters
 */

#define DEFAULT_THETA 0.5 
#define DEFAULT_DT 0
#define DEFAULT_DTIME 0.0001
#define DEFAULT_EPS 0.05
#define DEFAULT_TOL 1.0


#define DEFAULT_PPC 1000
#define DEFAULT_PPB 10
#define DEFAULT_KILLAT 10
#define DEFAULT_CHUNK_DEPTH 3

#ifdef SPLASH_COMPATIBLE
#define DEFAULT_YIELD_PERIOD 100
#else
#define DEFAULT_YIELD_PERIOD 10
#endif

#define DEFAULT_TREE_PIECES_PER_PROC 8
#define DEFAULT_BALANCE_PERIOD 3

#define DEFAULT_COMBINE_FLUSH_COUNT 10
#define DEFAULT_COMBINE_FLUSH_PERIOD 10.0f
#define DEFAULT_DECOMP_PERIOD 1
#define DEFAULT_DECOMP_BITS 1
#define DEFAULT_PARTICLE_MSG_MAX_SIZE 1048576

#endif
